import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.cpp
oled_gui.cpp
vcom_cmd.c
bosh_bme280.c
w25q128.c
rgb.c
strref.c
util.c
vcom_send.c
cyclequeue.c
""")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
